### ISSUE TITLE
Mark as read

### ISSUE THREAD

**Issue by seanfarley** [lordpretzel/mu4e-views#6] opened 2020-10-07 22:12 UTC
It seems that using this (great!) package with xwidgets doesn't mark the message as read? Is this something I misconfigured?

**Comment by lordpretzel** [comment] 2020-10-08 00:11
Hi,

not sure why it does not do that for you. Can you let me know some information about your setup?

- `mu4e` version
- setting of `mu4e-views-next-previous-message-behaviour`

**Comment by seanfarley** [comment] 2020-10-08 22:04
Hi, thanks for the quick response! I have:

* `mu4e` - 1.5.5
* `mu4e-views-next-previous-message-behaviour` - `always-switch-to-views`

No matter what I set `mu4e-views-next-previous-message-behaviour` though, the behavior is that no messages are marked read

**Comment by lordpretzel** [comment] 2020-10-09 03:01
thanks, I am on 1.4.13. I will have to setup a test environment at some point to test different mu4e versions. I think this would be due to some change how marking as read works in newer mu4e versions since for me it does mark as read.

**Comment by seanfarley** [comment] 2020-10-09 18:52
Aha, yeah, that would do it. I downgraded and confirmed that marking read works.

**Comment by lordpretzel** [comment] 2020-12-29 02:21
Hi, I finally go around creating a docker-based testing environment for different mu versions. Currently it is commandline only though. I was able to fix the text and gnus methods for mu on master. I'll have to setup a graphical version to text xwidgets though. Until then I'll keep this open.

**Comment by gdr3941** [comment] 2021-08-28 15:35
I have been having the same issue of messages not being shown as read in 1.6.3 & 1.6.4
Looking through the code, I think I may have found the issue:
In `mu4e-views-mu4e-headers-view-message`, `mu4e~proc-view` is called like this:
`(mu4e~proc-view docid mu4e-view-show-images decrypt verify)`
Notice that the second argument is `mu4e-view-show-images`
Yet the function signature for `mu4e~proc-view` is:
`defun mu4e~proc-view (docid-or-msgid &optional mark-as-read decrypt verify)`
which seems to indicate that this argument actually should be whether or not to mark as read.
(and in my setup, I had `mu4e-view-show-images` as nil)
I have confirmed this by setting `mu4e-view-show-images` to t, and now messages are marked as read when I move through them in the header view.
Let me know if there is anything else I can do to help.

**Comment by lordpretzel** [comment] 2021-08-31 18:55
thanks for the investigation! I'll fix this. Just have to make sure which mu version introduced that change to make sure that older versions will still work and then test in my test environment.

**Closed as completed** 2021-12-18 16:54 UTC
Labels: bug
